Миграция данных из Dean v1 в новую версию.
Yamaxila/Dean-backend pull request #1
Opened 2024-11-14 14:12 UTC by battlecr33k

Добавлена миграция данных из Dean v1 в новую версию. Добавлены 2 поля в объект учебного плана. Добавлены билдеры для образований и родителей. Перенесены перечисления типов занятий из диспетчерской.

2024-11-14 17:49 UTC, Yamaxila requested changes
завтра подумаю над принятием изменений

2024-11-14 17:49 UTC, Yamaxila commented on v1.migrate/src/main/java/by/vstu/migrate/v1/service/migrate/StudentMigrateService.java
> +        return null;
это что?)

2024-11-14 17:49 UTC, Yamaxila commented on v1.migrate/src/main/java/by/vstu/dean/DeanV1DBConfig.java
> +public class DeanV1DBConfig {
это вызовет большие проблемы

2024-11-14 17:49 UTC, Yamaxila commented on v1.migrate/src/main/java/by/vstu/migrate/v1/adapters/json/V1LocalDateJsonAdapter.java
> +public class V1LocalDateJsonAdapter implements JsonSerializer<LocalDate>, JsonDeserializer<LocalDate> {
Почему бы просто не использовать адаптер из ядра?

2024-11-14 17:49 UTC, Yamaxila commented on v1.migrate/src/main/java/by/vstu/migrate/v1/service/migrate/AbsenceMigrateService.java
> +package by.vstu.migrate.v1.service.migrate;
названия сервисов могут путать при работе с модулем "old"

2024-11-14 17:49 UTC, Yamaxila commented on v1.migrate/src/main/java/by/vstu/migrate/v1/service/migrate/AbsenceMigrateService.java
> +        AbsenceModel a = this.convertSingle(v1AbsenceModel);
поздравляю, вы получили StackOverflowException

2024-11-14 18:05 UTC, battlecr33k commented on v1.migrate/src/main/java/by/vstu/migrate/v1/service/migrate/StudentMigrateService.java
> +        return null;
чтоб не расслаблялся

2024-11-14 18:06 UTC, battlecr33k commented on v1.migrate/src/main/java/by/vstu/dean/DeanV1DBConfig.java
> +public class DeanV1DBConfig {
ты говорил не добавлять конфиг, видимо забыл удалить

2024-11-14 18:07 UTC, battlecr33k commented on v1.migrate/src/main/java/by/vstu/migrate/v1/adapters/json/V1LocalDateJsonAdapter.java
> +public class V1LocalDateJsonAdapter implements JsonSerializer<LocalDate>, JsonDeserializer<LocalDate> {
прост

2024-11-14 18:08 UTC, battlecr33k commented on v1.migrate/src/main/java/by/vstu/migrate/v1/service/migrate/AbsenceMigrateService.java
> +        AbsenceModel a = this.convertSingle(v1AbsenceModel);
AI code assistant + больная голова

2024-11-14 22:43 UTC, Yamaxila commented on v1.migrate/src/main/java/by/vstu/dean/DeanV1DBConfig.java
> +public class DeanV1DBConfig {
я реально такое сказал? просто как тогда вытягивать данные если они в другом Persistence unit'е? тут нужно просто с названиями бинов разобраться и пакет поменять

2024-11-15 09:29 UTC, Yamaxila requested changes
вроде всё отсмотрел

2024-11-15 09:29 UTC, Yamaxila commented on models/src/main/java/by/vstu/dean/enums/ELessonType.java
> +    LECTURE(0),
почему LECTURE начинается с 0, а не с 1?

2024-11-15 09:29 UTC, Yamaxila commented on v1.migrate/pom.xml
> +        <maven.compiler.source>19</maven.compiler.source>
версия jdk - 17, а не 19

2024-11-15 09:48 UTC, Yamaxila approved these changes

2024-11-15 09:49 UTC, merged